[package]
name = "zipurat"
version = "0.1.0"
edition = "2024"

[dependencies]
age = "0.11.1"
anyhow = "1.0.98"
blake3 = "1.8.2"
clap = { version = "4.5.38", features = ["derive"] }
humansize = "2.1.3"
indicatif = "0.17.11"
num_cpus = "1.16.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
simd-json = "0.15.1"
ssh2 = "0.9.5"
url = "2.5.4"
zstd = { version = "0.13.3", features = ["zstdmt"] }
